#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2020.1.14f1"
#define UNITY_VERSION_DIGITS "2020.1.14"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2020
#define UNITY_VERSION_MAJ 1
#define UNITY_VERSION_MIN 14
#define UNITY_IS_BETA 0
